# Copyright 2020 Wayback Archiver. All rights reserved.
# Use of this source code is governed by the GNU GPL v3
# license that can be found in the LICENSE file.
#
name: wayback

version: 'git'

summary: A toolkit to upload files to IPFS pinning services.

description: |
  A toolkit for snapshot webpage to the Wayback Machine.
  Website https://github.com/wabarc/wayback

base: core18
grade: stable
confinement: strict
compression: lzo
architectures:
  #- build-on: [i386, amd64, arm64, armhf, ppc64el, s390x]
  - build-on: amd64

parts:
  wayback:
    plugin: go
    source: https://github.com/wabarc/wayback.git
    go-importpath: github.com/wabarc/wayback/cmd/wayback

apps:
  wayback:
    command: wayback
    plugs:
      - home
      - network
      - network-bind
