name: Dispatch

on:
  release:
    types: [published]

jobs:
  release-brew:
    if: github.repository == 'wabarc/wayback'
    name: Repository Dispatch
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch repository in wabarc/aur
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: wabarc/homebrew-wayback
        event-type: publish
        token: ${{ secrets.PAT_WORKFLOW }}
        client-payload: '{"from": "${{ github.repository }}", "channel": "stable"}'

