name: Snapcraft

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  schedule:
    - cron: '0 0 * * *'

jobs:
  snapcraft:
    if: github.repository == 'wabarc/wayback'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - linux/amd64
          - linux/386
          #- linux/arm64
          #- linux/arm/v7
          #- linux/ppc64le
          #- linux/s390x
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - id: build
        name: Build Snap
        run: |
          # Enable docker daemon support for --platform parameter
          echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json > /dev/null
          sudo systemctl restart docker

          # Configure qemu-user-static
          docker run --rm --tty \
            --security-opt apparmor:unconfined \
            --cap-add SYS_ADMIN \
            multiarch/qemu-user-static --reset -p yes

          # Run snapcraft
          docker run --rm --tty \
            --security-opt apparmor:unconfined \
            --cap-add SYS_ADMIN \
            --device /dev/fuse \
            --volume /sys \
            --volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
            --volume $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            --workdir $GITHUB_WORKSPACE \
            --platform "${{ matrix.architecture }}" \
            --env PLAYTEST="${{ matrix.playtest }}" \
            diddledan/snapcraft:core18

          echo ::set-output name=snap::$(find $GITHUB_WORKSPACE -maxdepth 1 -type f -name "*.snap" | head -n1)

      - if: startsWith(github.ref, 'refs/tags/')
        uses: snapcore/action-publish@v1
        name: Release Snap
        with:
          store_login: ${{ secrets.SNAPCRAFT_TOKEN }}
          snap: ${{ steps.build.outputs.snap }}
          release: stable,candidate,beta,edge

      - if: ${{ github.event_name == 'schedule' }}
        uses: snapcore/action-publish@v1
        name: Release Snap for edge channel
        with:
          store_login: ${{ secrets.SNAPCRAFT_TOKEN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
